


var learnings = {
  "Introduction": { category: "intro", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.", image: "promotionImage/meuh.jpeg" },
  "Pourquoi": { category: "intro", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/mines_2.jpeg" },
  "Les femmes dans la société": { category: "Partie 1", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/maman.jpg" },
  "Les droits des femmes": { category: "Partie 1", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/egalite.jpg" },
  "Les figures féministes": { category: "Partie 1", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/simone_veil.jpg" },
  "L'ieseg en 2mots": { category: "intro", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/simone_veil.jpg" },
  "WW en deux mots": { category: "intro", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/simone_veil.jpg" },
  "Les neo-féministes": { category: "Partie 1", length: "1min 32s", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium feugiat nibh eu mollis. Fusce vitae lacinia eros. Donec auctor placerat turpis. Etiam tempus nulla a leo pharetra, id vulputate purus imperdiet. Duis efficitur aliquam vehicula. Nunc id diam venenatis ligula auctor varius. Quisque eget convallis nisi. Praesent pretium, dolor at posuere aliquet, magna risus sodales eros, ac convallis lorem nisl non orci. Nunc sit amet sem aliquam orci iaculis ultrices.",  image: "promotionImage/simone_veil.jpg" },
}

